# Практическая работа. Начало работы с библиотекой NumPy

Numpy — это библиотека с открытым исходным кодом для эффективной работы с массивами. Это критически важная библиотека обработки данных в Python, многие другие библиотеки зависят от нее.

Некоторые из преимуществ Numpy:

- Математические операции с объектами ndarray в NumPy выполняются до 50 раз быстрее, чем перебор собственных списков Python с использованием циклов. Повышение эффективности в первую очередь связано с тем, что NumPy хранит элементы массива в упорядоченном едином месте в памяти, устраняя избыточность за счет того, что все элементы относятся к одному типу, и в полной мере использует современные процессоры. Преимущества в эффективности становятся особенно очевидными при работе с массивами с тысячами или миллионами элементов, что довольно стандартно для науки о данных.

- Библиотека предлагает синтаксис индексирования для простого доступа к частям данных в массиве.

- NumPy содержит встроенные функции, которые улучшают качество жизни при работе с массивами и математикой, такие как функции для линейной алгебры, преобразования массивов и матричной математики.

- Для большинства математических операций требуется меньше строк кода, чем для собственных списков Python.

### Цель практической работы:

В этой работе нужно познакомится с основными методами библиотеки NumPy для обработки числовых данных.


Практическая работа предоставляется на проверку в виде блокнота Jupiter Notebook с сформированными ответами в кодовых ячейках и вычисленным результатом. Ячейки с заданиями удалять не нужно.

### Инструментарий

Работа может выполняться с использованием:
- Сервиса Google Colab (обработка блокнотов формата Jupiter Notebook)
- Локального сервера Jupiter Notebook или Jupiter Lab (обработка блокнотов формата Jupiter Notebook)
- Редактора VS Studio Code с установленными плагинами языка Python.

# 1. Базовые операции с NumPy

1. Импортируйте пакет numpy под именем np

In [2]:
import numpy as np

2. Распечатайте версию numpy

In [3]:
np.__version__

'2.0.2'

3. Создайте вектор размера 10, заполненный нулями

In [4]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. Создайте вектор размера 20, заполненный случайными числами от 1 до 10, распределенными по равномерному закону

In [16]:

vector1 = np.random.randint(1, 10, 20)
print(vector1)

[4 1 5 9 1 4 5 3 9 1 7 7 7 8 9 9 8 8 5 6]


5. Выполните нарезку вектора п.4 на два вектора по 10 элементов

In [17]:
vector11 = vector1[:10]
vector12 = vector1[10:]
print("Изначальный вектор:", vector1)
print("Первый вектор:", vector11)
print("Второй вектор:", vector12)

Изначальный вектор: [4 1 5 9 1 4 5 3 9 1 7 7 7 8 9 9 8 8 5 6]
Первый вектор: [4 1 5 9 1 4 5 3 9 1]
Второй вектор: [7 7 7 8 9 9 8 8 5 6]


6. Создайте вектор со значениями от 3 до 103 размерностью в 1200 элементов

In [18]:
vector2 = np.linspace(3, 103, 1200)
print(vector2)

[  3.           3.08340284   3.16680567 ... 102.83319433 102.91659716
 103.        ]


7. Разделите вектор п.6 на три части и переверните центральную часть

In [19]:
part1 = vector2[:400]
part2 = vector2[400:800]
part3 = vector2[800:]

part2_reversed = part2[::-1]


print("Первая часть:", part1)
print("Перевернутая центральная часть:", part2_reversed)
print("Третья часть:", part3)

Первая часть: [ 3.          3.08340284  3.16680567  3.25020851  3.33361134  3.41701418
  3.50041701  3.58381985  3.66722269  3.75062552  3.83402836  3.91743119
  4.00083403  4.08423686  4.1676397   4.25104254  4.33444537  4.41784821
  4.50125104  4.58465388  4.66805671  4.75145955  4.83486239  4.91826522
  5.00166806  5.08507089  5.16847373  5.25187656  5.3352794   5.41868224
  5.50208507  5.58548791  5.66889074  5.75229358  5.83569641  5.91909925
  6.00250209  6.08590492  6.16930776  6.25271059  6.33611343  6.41951626
  6.5029191   6.58632193  6.66972477  6.75312761  6.83653044  6.91993328
  7.00333611  7.08673895  7.17014178  7.25354462  7.33694746  7.42035029
  7.50375313  7.58715596  7.6705588   7.75396163  7.83736447  7.92076731
  8.00417014  8.08757298  8.17097581  8.25437865  8.33778148  8.42118432
  8.50458716  8.58798999  8.67139283  8.75479566  8.8381985   8.92160133
  9.00500417  9.08840701  9.17180984  9.25521268  9.33861551  9.42201835
  9.50542118  9.58882402  9.67222686 

8. Найдите индексы ненулевых элементов из вектора вида [1, 2, 0, 0, 4, 0, ...], размерностью в 100 элементов и заполненного случайными значениями от 0 до 10

In [21]:
vector3 = np.random.randint(0, 11, 100)
index = np.nonzero(vector3)[0]

print("Вектор:\n", vector3)
print("\nИндексы ненулевых элементов:\n", index)

Вектор:
 [ 8  7 10 10  7  0  4  4  7  6  7 10  7  8  9 10  7  3  0  6  6  0  4 10
  4  0  3  8  6  9  1  5  9  2 10  0  8  8  0  0  4  7  0  0  1  7  8  7
  2  9  4  6  4  8 10  3  0  0  5 10  2  8  0  6  0  6  8  5  7 10  5  6
  1  8 10  3  2  5  0  0  4  2  0  4  3  9  1  4  4  5  0  3  8  5  7  6
  0  6  3  4]

Индексы ненулевых элементов:
 [ 0  1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 19 20 22 23 24 26 27
 28 29 30 31 32 33 34 36 37 40 41 44 45 46 47 48 49 50 51 52 53 54 55 58
 59 60 61 63 65 66 67 68 69 70 71 72 73 74 75 76 77 80 81 83 84 85 86 87
 88 89 91 92 93 94 95 97 98 99]


9. Создайте матрицу 3x3 со случайными значениями от 0 до 8

In [22]:
import numpy as np

matrix = np.random.randint(0, 9, (3, 3))
print(matrix)

[[7 4 1]
 [2 8 2]
 [5 7 0]]


10.  Умножьте матрицу п.9 на число 2.5 и проделайте операцию вычитания из каждого элемента матрицы значения 1.3

In [23]:
matrix1 = matrix * 2.5
result = matrix1 - 1.3

print(" Исходная матрица:\n", matrix)
print("\n Итоговая матрица:\n", result)

 Исходная матрица:
 [[7 4 1]
 [2 8 2]
 [5 7 0]]

 Итоговая матрица:
 [[16.2  8.7  1.2]
 [ 3.7 18.7  3.7]
 [11.2 16.2 -1.3]]


11.  Создайте массив 3x3x3, заполненный случайными значениями (от 0 до 10)

In [24]:
array = np.random.randint(0, 11, (3, 3, 3))
print(array)

[[[ 3  6  9]
  [ 6  2  6]
  [ 3  1  6]]

 [[ 9  6  8]
  [10  2 10]
  [ 2  4  9]]

 [[ 7  7  0]
  [ 9  7 10]
  [ 3  8  4]]]


12.  Создайте массив 10x10 со случайными значениями (от -100 до 100) и найдите минимальное и максимальное значения массива

In [28]:
array1 = np.random.randint(-100, 101, (10, 10))
min_value = np.min(array1)
max_value = np.max(array1)

print("Массив:\n", array1)
print("\nМинимум:", min_value)
print("Максимум:", max_value)

Массив:
 [[  37  -66  -36   95  100 -100   28  -77  -83  -28]
 [ -80 -100  -68  -98   42   70   96  -70  -94  -74]
 [  86   90   10  -30  -11   46   41  -46   64  -38]
 [  53  -86  -23   39   91  -39  -39  -63  -72   71]
 [  60   35  -47  -46   54   91  -21   92  -75  -95]
 [  21   81  -54  -61  -64  -44   22   71  -79  -40]
 [  25   80  -72    3   83   83   41  -50  -75   98]
 [  29  -84   53   21  -34  -22  -34  -97  -58   20]
 [  69  -50   25  -63   66   26  -87   56  -84   91]
 [ -80   57  -71  -37  -62  -92   77  -15  -27   27]]

Минимум: -100
Максимум: 100


13.  Создайте две матрицы 3х6 и 6х3, заполненные случайными значениями (от -10 до 10) и найдите их скалярное произведение

In [33]:
A = np.random.randint(-10, 11, (3, 6))
B = np.random.randint(-10, 11, (6, 3))
resultat = np.dot(A, B)

print("Матрица A (3x6):\n", A)
print("\nМатрица B (6x3):\n", B)
print("\nРезультат A * B (3x3):\n", resultat)

Матрица A (3x6):
 [[ -9 -10   7   0   0  -8]
 [ -3   7  -4   1  -2   9]
 [-10  10 -10  -8   8   4]]

Матрица B (6x3):
 [[ -6   2   4]
 [-10   3  10]
 [ -8   1   4]
 [  6   9  -4]
 [ -4  -9   5]
 [  4  -6  -8]]

Результат A * B (3x3):
 [[  66    7  -44]
 [  30  -16  -44]
 [ -24 -168   60]]


14.  Сохраните результат скалярного произведения п.13 в файл формата CSV с разделителями в виде пробела

In [34]:
np.savetxt("result.csv", resultat, delimiter=" ", fmt="%d")

15.  Создайте матрицу 20х20, заполненную случайными значениями от -5 до 5 и вычислите определитель (детерминант) матрицы, используя библиотеку NumPy

In [38]:
matrix2 = np.random.randint(-5, 6, (20, 20))
det = np.linalg.det(matrix2)

print("Матрица:\n", matrix2)
print("\nОпределитель:", det)

Матрица:
 [[-2  4 -1  3  1  3 -3 -2 -1 -4 -1  3  2  3 -3  5 -2 -2 -5 -5]
 [ 1  2 -3 -5  1  4  5 -1  5 -5  5  2 -4  0  1  2 -3 -5  5  1]
 [ 3  0 -3  5 -1  0 -2 -3  2  2  5  5 -4 -5  4  2  1  3 -5 -3]
 [ 1 -5  2 -2  3 -2  4 -3  5  1 -2  5 -4  3  2  1 -4 -2 -3  4]
 [ 0 -4 -1 -2 -3  0  5 -1  1  0  5  2 -1  0  5 -2  3 -3 -3 -5]
 [ 5  5  2 -4 -3  3  2  5  4  5  2 -2 -4  5  5 -2 -1 -3  4  3]
 [-3 -3  5 -3  5  3  0  2  4  5 -5 -5 -5  0  5  5 -2  0  3 -4]
 [-1  0 -5 -5 -5 -4  2 -1  1  0  0  5  3  5  2  2  1  4 -1  1]
 [ 1 -1  4 -3 -1  2 -1 -5 -3 -3 -3  3  0  0 -5  5 -4 -5  5  5]
 [ 2 -2 -4  1  1  2  1  3  3  3 -1  2 -5  2 -3  3  5  5 -3 -3]
 [-3  5  5  3 -1  0  1  1  4 -4  5 -2  4 -4  2  3 -4  4  0 -4]
 [-1  2  3  3  3  3 -4  2  2 -3 -2  5  2  3  2  1 -1  0 -4 -1]
 [ 5  0 -2  4  1 -4 -5  3  1 -4 -4  5  3 -5  4  1 -4  2 -5  1]
 [ 4  1  5  1  2  5 -1  2 -5  3 -5 -5 -4  4  5  0 -5 -2 -1  2]
 [ 0  4  5  1  1 -1  2 -4 -1  1  0 -5  4  3 -5  3 -4  4 -4 -3]
 [ 1 -2 -1 -4 -4 -5  0 -3 -1  5  2 -1  1 -2  